#!/usr/bin/env bash
# make-swe-env.sh — generate a SWE environment directory from any git repo.
#
# Usage:
#   ./make-swe-env.sh <git-url> <sha> <install-cmd> <test-cmd> [name]
#
# Example:
#   ./make-swe-env.sh https://github.com/pallets/click.git \
#       b2e30a175449cfda909ee4fbf4a29a6a071cad53 \
#       'pip install -e . pytest' \
#       'python -m pytest -q'
#
# Emits swe/<name>/ (default name: swe-<repo basename>) containing a
# Dockerfile that checks the repo out at exactly <sha>, runs <install-cmd>,
# and runs <test-cmd> at build time (a red suite fails the build), plus
# env.yaml, README.md, and a tasks.jsonl.example stub.

set -euo pipefail

usage() {
  echo "usage: $0 <git-url> <sha> <install-cmd> <test-cmd> [name]" >&2
  exit 2
}

[ "$#" -ge 4 ] || usage

GIT_URL=$1
SHA=$2
INSTALL_CMD=$3
TEST_CMD=$4

repo_base=$(basename "$GIT_URL" .git)
NAME=${5:-swe-$repo_base}

case "$SHA" in
  *[!0-9a-f]*|"")
    echo "error: <sha> must be a full lowercase commit SHA (got: $SHA)" >&2
    exit 1
    ;;
esac
if [ "${#SHA}" -ne 40 ]; then
  echo "error: <sha> must be the full 40-character commit SHA (got ${#SHA} chars)" >&2
  exit 1
fi

script_dir=$(cd "$(dirname "$0")" && pwd)
out_dir="$script_dir/$NAME"

if [ -e "$out_dir" ]; then
  echo "error: $out_dir already exists" >&2
  exit 1
fi

mkdir -p "$out_dir"

cat > "$out_dir/Dockerfile" <<EOF
# $NAME: $repo_base frozen at $SHA with dependencies installed and the test
# suite green at build time. Fork per rollout; grade candidate patches by
# running the suite (or a task-specific subset).
# Generated by swe/make-swe-env.sh — edit freely, it's yours now.
FROM python:3.12-slim@sha256:c3d81d25b3154142b0b42eb1e61300024426268edeb5b5a26dd7ddf64d9daf28

ENV PYTHONUNBUFFERED=1 \\
    PIP_NO_CACHE_DIR=1

RUN apt-get update \\
 && apt-get install -y --no-install-recommends git ca-certificates \\
 && rm -rf /var/lib/apt/lists/*

ARG REPO_URL=$GIT_URL
ARG REPO_SHA=$SHA

# Fetch exactly the pinned commit and verify we got it.
RUN git init -q /repo \\
 && cd /repo \\
 && git remote add origin "\$REPO_URL" \\
 && (git fetch -q --depth 1 origin "\$REPO_SHA" || git fetch -q origin) \\
 && git checkout -q "\$REPO_SHA" \\
 && [ "\$(git rev-parse HEAD)" = "\$REPO_SHA" ]

WORKDIR /repo

RUN $INSTALL_CMD

# The environment contract: the suite is green when the image builds.
RUN $TEST_CMD

CMD ["sleep", "infinity"]
EOF

cat > "$out_dir/env.yaml" <<EOF
id: $NAME
name: SWE - $repo_base @ ${SHA:0:8}
description: $repo_base frozen at ${SHA:0:8} with dependencies installed and the test suite green at build; grade patches by running the suite.
image: ghcr.io/collimateai/env-$NAME
tags:
  - swe
  - rl
  - exec-grader
probe: bash -lc "cd /repo && git rev-parse HEAD && $TEST_CMD"
EOF

# Bake-time ready command: when the test command is pytest-based, pre-collect
# the suite so forks start with imports resolved and collection cached - the
# grading exec then pays only for the tests themselves.
case "$TEST_CMD" in
  pytest*|"python -m pytest"*)
    cat >> "$out_dir/env.yaml" <<READYEOF
ready:
  cmd: bash -lc "cd /repo && $TEST_CMD --collect-only -q >/dev/null"
READYEOF
    ;;
esac

cat > "$out_dir/README.md" <<EOF
# $NAME

\`$repo_base\` frozen at \`$SHA\`, checked out at \`/repo\` with dependencies
installed. The test suite runs during \`docker build\` — a red suite fails the
build, so a published image is a green world.

- Install: \`$INSTALL_CMD\`
- Grade:   \`cd /repo && $TEST_CMD\`

Fork this environment once per rollout, push the candidate's edited files with
\`files=[...]\`, run the grading command, score the result. See
[\`../grading.py\`](../grading.py) for the complete loop and
[\`tasks.jsonl.example\`](tasks.jsonl.example) for the task-record shape.
EOF

cat > "$out_dir/tasks.jsonl.example" <<EOF
{"instance_id": "$NAME-0001", "repo": "$repo_base", "base_commit": "$SHA", "problem_statement": "<one-paragraph bug description the policy sees>", "target_files": ["<path/inside/repo.py>"], "grading_command": "cd /repo && $TEST_CMD", "fail_to_pass": ["<tests the fix must turn green>"], "pass_to_pass": ["<tests that must stay green>"]}
EOF

echo "wrote $out_dir/"
echo "  Dockerfile           (checkout $repo_base @ ${SHA:0:12}, install, run suite)"
echo "  env.yaml             (catalog metadata)"
echo "  README.md"
echo "  tasks.jsonl.example  (fill in real task records)"
echo
echo "next: docker build \"$out_dir\" locally, then open a PR."
